### ISSUE TITLE
Tests reference a file which is not included in the tarball

### ISSUE THREAD

**Issue by sebix** [facelessuser/bracex#40]
The tests depend on a text file:
https://github.com/facelessuser/bracex/blob/8edd0c52847188fb116a6fb507d8d359c3cabd93/tests/test_brace.py#L22
which is not part of the sdist tarball on PyPI. It seems the build process of poetry only takes in python files by default.

I think a simple include in the pyproject.toml would be sufficient: https://python-poetry.org/docs/pyproject/#include-and-exclude

**Comment by sebix** [comment]
The file was previously included in the tarballs, but the MANIFEST.in entry got removed in #39

**Comment by facelessuser** [comment]
Ah, yeah, that was a mistake. I didn't run the tests from the tar ball to verify.

**Comment by facelessuser** [comment]
@gir-bot remove S: triage
@gir-bot add T: maintenance
